// Code generated by yy. DO NOT EDIT.

// Copyright 2021 The web2go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package main

import (
	"go/token"
)

// Program represents data reduced by production:
//
//	Program:
//	        "program" IDENTIFIER
type Program struct {
	tok  tok
	tok2 tok
}

// String implements fmt.Stringer.
func (n *Program) String() string { return prettyString(n) }

// Position reports the position of the first component of n, if available.
func (n *Program) Position() (r token.Position) {
	if n == nil {
		return r
	}

	if p := n.tok.Position(); p.IsValid() {
		return p
	}

	return n.tok2.Position()
}

// program represents data reduced by production:
//
//	program:
//	        Program
type program struct {
	Program *Program
}

// String implements fmt.Stringer.
func (n *program) String() string { return prettyString(n) }

// Position reports the position of the first component of n, if available.
func (n *program) Position() (r token.Position) {
	if n == nil {
		return r
	}

	return n.Program.Position()
}
