// Code generated by yy. DO NOT EDIT.

// Copyright 2021 The web2go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package main

import (
	"fmt"
)

func ExampleProgram_case0() {
	fmt.Println(exampleAST(2, "program a"))
	// Output:
	// TODO 2 "program a"
}

func Exampleprogram_case0() {
	fmt.Println(exampleAST(1, "program a"))
	// Output:
}
